server:
  port: 1000

spring:
  datasource:
    url: jdbc:mysql://localhost:3309/online_book_store
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

